exParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tareaApp.urls')),
    path('tareasApp/',include('tareasApp.urls'))
]

tareaApp/urls.py
from django.urls import path
from . import views

app_name='tareaApp'

urlpatterns = [
    path('',views.index,name='index'),
    path('nuevaTarea',views.nuevaTarea,name='nuevaTarea')
]

tareasApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
]

tareaApp/models.py
from django.db import models

# Create your models here.

tareasApp/models.py
from django.db import models

# Create your models here.

tareaApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

lista_tareas = [
    ['DESCANSAR','20-12-2024','EN PROGRESO','ALEXANDER'],
  
]

# Create your views here.
def index(request):
    return render(request,'index.html',{
        'lista_tareas':lista_tareas
    })

def nuevaTarea(request):
    if request.method == 'POST':
        print(request.POST)
        nombre = request.POST.get('nombre')
        fechaFin = request.POST.get('fecha')
        descripcion = request.POST.get('descripcion')
        
        print(nombre)
        print(fechaFin)
        print(descripcion)
        lista_tareas.append([nombre,descripcion,fechaFin,'Responsable'])
        return HttpResponseRedirect(reverse('tareaApp:index'))
    return render(request,'nuevaTarea.html')

tareasApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Bienvenidos a Django")

tareaApp/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Gestor de tareas</title>
        <style>
            table {
                width: 80%;
                border-collapse: collapse;
            }

            table, th, td {
                border: 1px solid;
            }
        </style>
    </head>
    <body>
        <div style="text-align: center;">
            <h1>VISTA PRINCIPAL - GESTOR DE TAREAS</h1>
        </div>
        <div style="display: flex; flex-direction: row; justify-content: space-around;">
            <a href="{% url 'tareaApp:nuevaTarea' %}">
                <button style="width: 120px;">Nueva tarea</button>
            </a>
            <a>
                <button style="width: 120px;">Ver historico</button>
            </a>
        </div>
        <br>
        <div style="display: flex; flex-direction: row; justify-content: center;">
            <table>
                <thead>
                    <th>Nombre</th>
                    <th>Fecha de fin</th>
                    <th>Estado</th>
                    <th>Responsable</th>
                    <th>Finalizar 
                        <button style="width: 120px; display: flex;">finalizar</button>
                    </th>
                    
                </thead>
                <tbody>
                    {% for tarea in lista_tareas %}
                    <tr>
                        <td>{{ tarea.0 }}</td>
                        <td>{{ tarea.1 }}</td>
                        <td>{{ tarea.2 }}</td>
                        <td>{{ tarea.3 }}</td>
                        <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>

tareaApp/templates/nuevaTarea.html
<!DOCTYPE html>
<html>
    <head>
        <title>Nueva tarea</title>
    </head>
    <body>
        <div style="text-align: center;">
            <h1>CREAR NUEVA TAREA</h1>
        </div>
        <br>
        <div>
            <a href="{% url 'tareaApp:index' %}">
                <button>Regresar</button>
            </a>
        </div>
        <br>
        <div>
            <form style="display: flex; flex-direction: row; width: 100%; justify-content: center;" method="post" action="{% url 'tareaApp:nuevaTarea' %}">
                {% csrf_token %}
                <div style="width: 60%;">
                    <div style="display: flex; flex-direction: row; justify-content: space-between;">
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Nombre</label>
                            <input type="text" name="nombre" required>
                        </div>
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Descripcion</label>
                            <input type="text" name="descripcion" required>
                        </div>
                    </div>
                    <div style="display: flex; flex-direction: row; justify-content: space-between;">
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Fecha de fin</label>
                            <input type="date" name="fecha" required>
                        </div>
                        <div style="display: flex; flex-direction: column; width: 45%;">
                        </div>
                    </div>
                    <div style="display: flex; flex-direction: column; justify-content: space-between; width: 45%;">
                        <label>Responsable</label>
                        <input type="text" name="responsable" required>
                    </div>
                    <br>
                    <div>
                        <input type="submit" value="Crear tarea">
                    </div>
                </div>
            </form>
        </div>
    </body>
</html>